name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set up Cloud SQL Proxy
        id: cloud-sql-proxy
        uses: google-github-actions/setup-cloud-sql-proxy@v1
        with:
          instance_connection_name: animated-zenith-428816-g1:europe-west1:xpirio-site-db
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          port: 5432

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Retrieve DB Password from Secret Manager
        id: get-secret
        run: |
          echo "DATABASE_PASSWORD=$(gcloud secrets versions access latest --secret=DATABASE_PASSWORD)" >> $GITHUB_ENV

      - name: Run
        run: node start
